#!/usr/bin/env sh

docker build -t vega-widget-dev .
docker run \
  -it --rm --ipc=host \
  -p 8888:8888 \
  --mount "type=bind,source=$(pwd)/src,target=/code/src" \
  --mount "type=bind,source=$(pwd)/test,target=/code/test" \
  --mount "type=bind,source=$(pwd)/index.ts,target=/code/index.ts" \
  --mount "type=bind,source=$(pwd)/vega-widget.ts,target=/code/vega-widget.ts" \
  --mount "type=bind,source=$(pwd)/yarn.lock,target=/code/yarn.lock" \
  vega-widget-dev "$@"
